/*
 * Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "hal_data.h"
#include "pd_axi_on.h"
#include "common_utils.h"
#include "i2c_slave.h"
#define MODULE_NAME		"r_riic_slave"

/*******************************************************************************************************************//**
 * @addtogroup r_riic_slave_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t          err                  =  FSP_SUCCESS;
    fsp_pack_version_t version              = {RESET_VALUE};

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION,version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /*  I2C master and slave driver initialization */
    err = init_i2C_driver();
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* RIIC Master and Slave initialization failed  */
        APP_ERR_PRINT("\r\n ** RIIC driver initialization FAILED ** \r\n");

        /* Turn ON LED */
        set_led(LED_ON);

        APP_ERR_TRAP(err);
    }

    while(true)
    {
        /* Performs on I2C slave read write operation */
        err = process_slave_WriteRead();

        /*
         * Perform clean_up - On slave i2c read write operation failure
         * Note: For Demonstration Purpose the failure ends up with TRAP.
         * Note: This can be handled in many ways as per the Application needs
         */
        if (FSP_SUCCESS != err)
        {
            /* print RTT message */
            APP_ERR_PRINT ("\r\n **I2C slave transaction Failed, closing open modules ** \r\n");

            /* de-initialize opened RIIC module */
            deinit_i2c_driver();
            APP_ERR_TRAP(err);
        }

        /* 1 Seconds Wait time to recognize LED toggling between successive Read and Write operations. */
        R_BSP_SoftwareDelay(TIME_DELAY, BSP_DELAY_UNITS_MILLISECONDS);
    }
}
/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* Allow access to IP beyond AXI */
        pd_all_on_postproc_axi();
    }
}

/*******************************************************************************************************************//**
 * @} (end addtogroup r_riic_slave_ep)
 **********************************************************************************************************************/
