/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright 2024 Renesas Electronics Corporation and/or its affiliates.  All Rights Reserved.
 *
 * This software and documentation are supplied by Renesas Electronics Corporation and/or its affiliates and may only
 * be used with products of Renesas Electronics Corp. and its affiliates ("Renesas").  No other uses are authorized.
 * Renesas products are sold pursuant to Renesas terms and conditions of sale.  Purchasers are solely responsible for
 * the selection and use of Renesas products and Renesas assumes no liability.  No license, express or implied, to any
 * intellectual property right is granted by Renesas.  This software is protected under all applicable laws, including
 * copyright laws. Renesas reserves the right to change or discontinue this software and/or this documentation.
 * THE SOFTWARE AND DOCUMENTATION IS DELIVERED TO YOU "AS IS," AND RENESAS MAKES NO REPRESENTATIONS OR WARRANTIES, AND
 * TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPLICITLY OR IMPLICITLY,
 * INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, WITH RESPECT TO THE
 * SOFTWARE OR DOCUMENTATION.  RENESAS SHALL HAVE NO LIABILITY ARISING OUT OF ANY SECURITY VULNERABILITY OR BREACH.
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL RENESAS BE LIABLE TO YOU IN CONNECTION WITH THE SOFTWARE OR
 * DOCUMENTATION (OR ANY PERSON OR ENTITY CLAIMING RIGHTS DERIVED FROM YOU) FOR ANY LOSS, DAMAGES, OR CLAIMS WHATSOEVER,
 * INCLUDING, WITHOUT LIMITATION, ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, PUNITIVE, OR INCIDENTAL DAMAGES; ANY
 * LOST PROFITS, OTHER ECONOMIC DAMAGE, PROPERTY DAMAGE, OR PERSONAL INJURY; AND EVEN IF RENESAS HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH LOSS, DAMAGES, CLAIMS OR COSTS.
 **********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "intc_irq_ep.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Board's user LED */
extern bsp_leds_t g_bsp_leds;
/* Boolean flag to determine switch is pressed or not.*/
extern volatile bool g_sw_press;

/*******************************************************************************************************************//**
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry (void) {
    fsp_err_t err                           = FSP_SUCCESS;
    bsp_io_level_t led_current_state        = (bsp_io_level_t) RESET_VALUE;
    fsp_pack_version_t version              = {RESET_VALUE};

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the RTT */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.major, version.minor, version.patch);
    APP_PRINT(EP_INFO);

    /* Initialize External IRQ driver*/
    err = intc_irq_init();
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** INTC IRQ INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable External IRQ driver*/
    err = intc_irq_enable();
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** INTC IRQ ENABLE FAILED ** \r\n");
        /* Close External IRQ module.*/
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == leds.led_count)
    {
        APP_PRINT("\r\nThere are no LEDs on this board\r\n");
        /* Close External IRQ module.*/
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* Main loop */
    while (true)
    {
        /* Toggle user LED  when user pushbutton is pressed*/
        if(true == g_sw_press)
        {
            /* Clear user pushbutton flag */
            g_sw_press = false;

            /* Notify that user pushbutton is pressed */
            APP_PRINT("\r\nUser Pushbutton Pressed\r\n");

            /* Read user LED  pin */
            for (uint32_t i = 0; i < g_bsp_leds.led_count; i++)
            {
                /* Get pin to toggle */
                bsp_io_port_pin_t pin = g_bsp_leds.p_leds[i];

                /* Read from this pin */
                err = R_IOPORT_PinRead(&g_ioport_ctrl, pin, &led_current_state);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT("** R_IOPORT_PinRead FAILED ** \r\n");
                    /* Close External IRQ module.*/
                    intc_irq_deinit();
                    APP_ERR_TRAP(err);
                }
            }

            /* Reverse LED pin state*/
            led_current_state ^= BSP_IO_LEVEL_HIGH;

            /* Toggle user LED */
            for (uint32_t i = 0; i < g_bsp_leds.led_count; i++)
            {
                /* Get pin to toggle */
                uint32_t pin = g_bsp_leds.p_leds[i];

                /* Write to this pin */
                err = R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)pin, led_current_state);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT("** R_IOPORT_PinWrite FAILED ** \r\n");
                    /* Close External IRQ module.*/
                    intc_irq_deinit();
                    APP_ERR_TRAP(err);
                }
            }
#if defined (BOARD_RA6T1_RSSK) || defined (BOARD_RA4W1_EK)
            if(BSP_IO_LEVEL_LOW == led_current_state)
#else
                if(BSP_IO_LEVEL_HIGH == led_current_state)
#endif
                {
                    /* Print LED Pin state */
                    APP_PRINT("LED State: High{ON}\r\n");
                }
                else
                {
                    /* Print LED Pin state */
                    APP_PRINT("LED State: Low{OFF}\r\n");
                }
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event) {
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}
